use anyhow::Result;
use async_trait::async_trait;

use super::Event;

/// Trait to handle events generated by solo machine
#[async_trait]
pub trait EventHandler: Sync + Send {
    /// Handles an event
    async fn handle(&self, event: Event) -> Result<()>;
}

pub struct NoopEventHandler;

#[async_trait]
impl EventHandler for NoopEventHandler {
    async fn handle(&self, _event: Event) -> Result<()> {
        Ok(())
    }
}
