//! Events generated by Stag API
mod builder;
mod event_handler;
mod event_types;
#[cfg(feature = "tracing-event-handler")]
mod tracing_event_handler;

#[cfg(feature = "tracing-event-handler")]
pub use self::builder::TracingEventHandler;
pub use self::{
    builder::EventHandlerConfig,
    event_handler::{EventHandler, NoopEventHandler},
    event_types::Event,
};
