genesis:
  chain_id: "mars-1"
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "practice empty client sauce pistol work ticket casual romance appear army fault palace coyote fox super salute slim catch kite wrist three hedgehog sign"
  - name: bob
    coins: ["10000token", "100000000stake"]
    mnemonic: "setup chicken slogan define emerge original sugar bitter suggest bicycle increase eager rather end predict relief moment burden lonely ginger umbrella secret toy trash"
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
init:
  app:
    grpc-web:
      enable-unsafe-cors: true
