name: Test Suite

on:
  push:
    branches: [ main ]

jobs:
  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - name: Test go installation
        run: go version
      - name: Install starport
        run: curl https://get.starport.network/starport! | bash
      - name: Test starport installation
        run: starport version
      - name: Scaffold test blockchain
        run: starport scaffold chain github.com/devashish/mars --no-module
      - name: Start test blockchain
        run: |
          cd mars
          starport chain serve &
      - name: Wait for test blockchain to start
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://0.0.0.0:26657/status
      - name: Verify test blockchain
        run: curl http://0.0.0.0:26657/status
