name: Test Suite

on:
  push:
    branches: [ main ]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - name: Test go installation
        run: go version
      - name: Install starport
        run: curl https://get.starport.network/starport! | bash
      - name: Test starport installation
        run: starport version
